create database careerhub;
USE CAREERHUB;
CREATE TABLE COMPANY(
	COMPANYID INT PRIMARY KEY,
    COMPANYNAME VARCHAR(25),
    LOCATION VARCHAR(25)
);
CREATE TABLE JOBLISTING (
    JOBID INT PRIMARY KEY,
    COMPANYID INT,
    JOBTITLE VARCHAR(25),
    JOBDESCRIPTION VARCHAR(50),
    JOBLOCATION VARCHAR(25),
    SALARY DECIMAL(10 , 2 ),
    JOBTYPE ENUM('FULL_TIME', 'PART_TIME','CONTRACT'),
    POSTEDDATE DATE,
    FOREIGN KEY (COMPANYID)
        REFERENCES COMPANY (COMPANYID)
);

CREATE TABLE APPLICANT(
	APPLICANTID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(25),
    LASTNAME VARCHAR(25),
    EMAIL VARCHAR(25),
	PHONE VARCHAR(25),
    RESUME VARCHAR(25)
);
CREATE TABLE JOBAPPLICATION(
	APPLICATIONID INT PRIMARY KEY,
    JOBID INT,
    APPLICANTID INT,
    APPLICATIONDATE DATE,
	COVERLETTER VARCHAR(50),
    FOREIGN KEY (JOBID)
        REFERENCES JOBLISTING (JOBID),
	FOREIGN KEY (APPLICANTID)
        REFERENCES APPLICANT (APPLICANTID)
);

alter table joblisting modify salary double;
alter table jobapplication modify applicationid int auto_increment;
alter table joblisting modify jobid int auto_increment;